### ISSUE TITLE
Better definition of used-by

### ISSUE THREAD

**Issue by alranel** [ruphy/publiccode.yml#2]
What should be listed under used-by? Only active deployments or also past ones?
Should we list the IPA codes instead of string names?

**Comment by bvhme** [comment]
Hey @alexrj, what are IPA codes? I've been going down the rabbit hole of trying to find standardised codes for PAs, but even the EU just recommends using verbose RDF descriptions ([ISA2 Core Vocalbularies](https://joinup.ec.europa.eu/release/core-location-vocabulary/100))...

The active/inactive part is indeed smart, and I'm wondering how maintenance of this section should work.

**Comment by rasky** [comment]
IPA codes are codes that uniquely identify a PA in Italy.

Personally, I don't think we want to create a strong semantic web of links here. The purpose of this key is just "advertising" the software is being used. The fact that it's left to the author of the software the burden to update this list is already telling -- the idea is that it's a marketing statement more than anything else. Obviously people can open PR upstream to add themselves to the list (we see this happening sometimes in open source projects), but I still expect this to be a best effort that is unlikely to be updated or exhaustive. So I'd rather err on the simple side.

**Comment by ruphy** [comment]
Clarified this issue in the documentation.
